### PR TITLE
Improved handling of retina sprites

### PR DESCRIPTION
**Pull request by pmgarman**
- Added additional media queries for better coverage of when to use the retina sprite
- Added sprite position for retina sprite

### CODE REVIEW

**Comment by pmgarman** [comment]
Had run into cases where the retina sprites positions were different from the non-retina sprite. Couldn't determine why it was out of order but didn't see any harm in adding `background-position` to the retina sprite either.

I have confirmed it's working as expected now for scss, the others I have not tested but attempted to updated based on the rest of the code. Didn't have a chance to update the tests either, which I assume will fail with the modified output.

**Comment by twolfson** [comment]
Thanks for taking the time to open this PR. Currently, we are trying to use as little code as possible for our media queries/positioning to reduce the footprint of `spritesmith`. This means this PR would cause harm by adding unnecessary new info.

As a result (and to patch this bug properly), can you provide an example of the issue you are seeing (e.g. CSS flavor, browser, normal/retina spritesheets)?

**Comment by twolfson** [comment]
Did some new research on the topic. It looks like we can switch to `min-resolution` over `min-device-pixel-ratio` but need to maintain `-webkit-min-device-pixel-ratio` for mobile browsers:

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Media_queries

http://www.w3.org/blog/CSS/2012/06/14/unprefix-webkit-device-pixel-ratio/

http://caniuse.com/#feat=css-media-resolution

**Comment by pmgarman** [comment]
Sure. This is being used in a WordPress theme by way of grunt-spritesmith. I created a [gist](https://gist.github.com/pmgarman/c3547c201c1b4963abee) with the Gruntfile.js, package.json, and a few links to screenshots of the resulting sprites as well as a screenshot of my images dir. I **think** everything is setup right and it's really really simple, I just don't know why the two sprites have images in reverse order.

**Comment by twolfson** [comment]
The problem you are encountering is due to lexicographical sorting by JS. It thinks that `.` is less than `-` so in the first array, `logo.png` is being sorted after `logo-white.png`. Whereas in the second, `2` is greater than `w`.

```
> var a = ['logo.png', 'logo-white.png'];
undefined
> a.sort();
[ 'logo-white.png', 'logo.png' ]
> var b = ['logo-2x.png', 'logo-white-2x.png'];
undefined
> b.sort();
[ 'logo-2x.png', 'logo-white-2x.png' ]
```

To fix your problem, I suggest renaming `logo.png` to `logo-1x.png` (and `logo-white-1x` for convention). That should fix up the sorting/ordering issues.

Aside from that, what was the reasoning for the new retina media queries?

**Comment by pmgarman** [comment]
Really it was just a "I'm already here and I use this in another mixin already, so I'll just drop it in" ... no "technical" reason beyond just assuming all the browsers "need" their own retina queries. No specific use case at the moment showing it isn't enough as is.

I'll update the file names and take it from there, also good to know now about the sorting and something to keep in mind in the future. I'll go ahead and close this - thanks for taking the time to write up an explaination!

**Comment by pmgarman** [comment]
Just confirming that renaming like you described worked out as expected.

**Comment by twolfson** [comment]
Cool, glad to hear everything worked out =) I might update the media queries based on what I discovered (e.g. `min-device-pixel-ratio`` is deprecated)

**Comment by twolfson** [comment]
Upon further review, it looks like we are already using the ideal combination. Yey =3

**Comment by pmgarman** [comment]
Awesome! If I find any cases where it doesn't seem to work, I'll be sure to let you know. Sounds like I'll have a hard time finding any though :)

**Pull request closed without merging**
